name: sontonizzarevbs
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^4.0.1
  on_audio_query: ^2.9.0
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  youtube_explode_dart: ^1.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg